### ISSUE TITLE
Adopt config.def.mk system instead of config.mk

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#11]
I have noticed that you use config.mk, which is tracked by git. It would be much better to have this file untracked by git so that changes made by the user don't get overwritten. The way I'd do this is to have a config.def.mk, then have a Makefile rule like this:

config.mk: config.def.mk
     cp config.def.mk config.mk

You can have a look at the Makefiles Soundpipe/Sporth to see how this is done.

**Comment by fennecdjay** [comment]
This is done now, along with a few improves in build system.
