### ISSUE TITLE
Binding to other languages 

### ISSUE THREAD

**Issue by scalarwaves** [fennecdjay/Gwion#112]
First of all thank you for making Gwion! I love ChucK and this project could be of great use to me. Recently I’ve been trying to create a C wrapper for ChucK to bind with a Rust library. It hasn’t been easy, though that’s not to say ChucK isn’t awesome. Is there a master header like *gwion.h* that would provide an API suitable for FFI with Rust?

**Comment by fennecdjay** [comment]
Brillant!
Actually not yet. There is *gwion_util.h* and *gwion_ast.h* for the libraries, and an actual *gwion.h* for an actual **Gwion** structure.
I've been thinking into unifying all these though.
Definitely gonna look at it soon and warn you.

**Comment by scalarwaves** [comment]
Wonderful. If you're interested, [ruckus](https://github.com/tonal-glyph/ruckus) is the Rust+ChucK project, which is part of a group of projects related to my WIP digital audio workstation [tgtracker](https://github.com/tonal-glyph/tgtracker). How does Gwions plugin system work with LLVM and all that? Is it similar to Chugins?

**Comment by fennecdjay** [comment]
I don't know anything about rust FFI, so I'm afraid I won't be able to help on this unless you get more specific ;-)
Anyway **Gwion** plugin system should be quite similar to **Chuck**'s. Just dynamic libraries loaded at runtime.
In **Gwion** case, you have to define an GWION_IMPORT function to define a class.
Note that you can also define a driver (e.g. sound ouput) with GWDRIVER and a module (e.g. coverage instrumentation or JIT) with GWMODINI and GWMODEND (both requiring defining GWMODSTR).
You can see actual usage of all this in src/lib (see [here](https://github.com/fennecdjay/Gwion/blob/master/src/lib/shred.c) as an example) and in [this directory](https://github.com/fennecdjay/Gwion/tree/master/tests/import)

**Comment by fennecdjay** [comment]
I had a quick look at **ruckus**, and I'm not quite sure what's going on there, but I think you should look [here](https://github.com/fennecdjay/Gwion/blob/master/src/main.c#L28-L42).
These few lines should enable you to start and run a gwion process. To add more files/strings, you'll need the functions in [compile.h](https://github.com/fennecdjay/Gwion/blob/master/include/compile.h).

Also [that](https://gist.github.com/fennecdjay/b98274766daef70ab4467c2b62e79511) might be of some help.

You'll almost certainly have to make some change to the Makefile (or anything else), please let me now.

**Comment by scalarwaves** [comment]
Indeed, libgwion.a or libgwion.so would be quite useful, if you could manage it.

**Comment by fennecdjay** [comment]
Looking at it :smile:

**Comment by fennecdjay** [comment]
Maybe you can add
``` Make
libgwion.a: ${lib_obj}
  ${AR} ${AR_OPT}
```
to your Makefile (line 74).

**Comment by scalarwaves** [comment]
When trying to add that to makefile I got a
`Makefile:74: *** missing separator.  Stop.`

**Comment by fennecdjay** [comment]
Ins't that because you pasted it and hence loosed the leading TAB of line 2?
Anyway I be pushing in a few minute. Hopefully you'll tell me then.

**Comment by scalarwaves** [comment]
Yep, that was the problem. I got it working by fixing the tab and adding libgwion.a to the all: target. When you push I'll pull your changes. This is really cool!

**Comment by fennecdjay** [comment]
I already pushed, just waited for [this](https://travis-ci.org/fennecdjay/Gwion/builds/532413888) to finish to warn you :+1:

**Comment by scalarwaves** [comment]
Ok, GCC and some Clang builds succeeded. Does the libgwion.a target need to be added to the all: target? Like this:
`all: options util/libgwion_util.a ast/libgwion_ast.a libgwion.a ${GW_OBJ} ${jit_obj}`

**Comment by fennecdjay** [comment]
Not yet.

...

Coming Soon :smiley: 


----------
Yes clang/windows builds fail due to some header inclusion issue I did not fix yet.

**Comment by scalarwaves** [comment]
Clang is no issue right now, I’m mostly using gcc.

**Comment by fennecdjay** [comment]
As I understand you might use **Gwion** inside [tgtracker](https://github.com/tonal-glyph/tgtracker). How do you plan sound output?

**Comment by scalarwaves** [comment]
That's still to be decided. I want tgtracker to be cross-platform as much as possible, so the current plan is to use Rust bindings [rsoundio](https://github.com/klingtnet/rsoundio) to [libsoundio](https://github.com/andrewrk/libsoundio), which can output to:
- JACK
- PulseAudio
- ALSA
- CoreAudio
- WASAPI

The other option is the Rust library [cpal](https://github.com/tomaka/cpal), which can output to:
- Linux (via ALSA)
- Windows
- macOS (via CoreAudio)
- iOS (via CoreAudio)
- Emscripten

I would really really like a Chuck-like language for livecoding in tgtracker, whether it's Chuck, Gwion, or both. I'm in a bit of a crazy mood where I'm coming up with all these ideas to add to tgtracker and feature bloat is a looming problem.

**Comment by fennecdjay** [comment]
So as far as I understand it, you'll do mixing in tg. You're gonna need a driver to input/ouput
data in/out **Gwion**. I'll be glad to help if it's the case.

**Comment by scalarwaves** [comment]
Yes thank you. I'm very new to systems programming so I need all the help I can get. I'll focus on audio IO and see if i can get some input and output streams and a mixer. I'll also setup bindgen to attempt codegen for gwion_all.h and see how that turns out.

**Comment by scalarwaves** [comment]
I'm setting up a copy of gwion tailored to my dev environment which can be very picky about some things _ugh_  As much as I love ChucK, the project layout is frustrating. I like how you've structured your code. Speaking of binding to other languages, have you ever thought about a Chuck => Gwion bridge? Since the syntax is sooo similar, shouldn't be too hard to translate one to the other.

**Comment by fennecdjay** [comment]
> I like how you've structured your code.
Happy to read that, I guess that's kind of a [point of view](https://bettercodehub.com/results/fennecdjay/Gwion).
I don't think one can achieve fully automatic *Chuck => Gwion* bridge easily.
(UAana's, STK, would need a matching plugin).
But a simple bash script could be handy :+1:

**Comment by fennecdjay** [comment]
If you're OK, @scalarwaves, I close this issue as we have a better place for this discussion.
