### ISSUE TITLE
Adding a Hello World Program to examples

### ISSUE THREAD

**Issue by Pranav2612000** [fennecdjay/Gwion#175]
**Describe the solution you'd like**
What do you think of adding a hello world program to examples? And mentioning how to run this file in the readme

**Additional context**
This would make it much easier for newcomers to run the basic hellow world program first.

**Comment by fennecdjay** [comment]
I think we'd better have a mini-tutorial in the README, after the build section, invite the user to type it's own **hello world** (but an example has to be supplied), save it, and show how to run it.
What to you think?
Would you fancy doing the REAMDE edits?

**Comment by fennecdjay** [comment]
Also, does it work on your machine?

It should, all CI test are green, but you never know you know ... :smiley:

**Comment by Pranav2612000** [comment]
> I think we'd better have a mini-tutorial in the README, after the build section, invite the user to type it's own **hello world** (but an example has to be supplied), save it, and show how to run it.
> What to you think?
> Would you fancy doing the README edits?

Yeah. Sure. Any other things that need to be added to it?

**Comment by Pranav2612000** [comment]
> Also, does it work on your machine?
> 
> It should, all CI test are green, but you never know you know ... smiley

Yes. It does. I forgot the dreaded semicolon before, so was throwing errors, but now it does work. Although, and this may be a minor issue, when the compilation failed due to the syntax error, an underline was being added to my terminal text. Should I create a new issue for this?

Any other non-documentation beginner-friendly issues I can work on?

**Comment by fennecdjay** [comment]
> when the compilation failed due to the syntax error, an underline was being added to my terminal text. Should I create a new issue for this?

Please do.

> Any other non-documentation beginner-friendly issues I can work on?

None out of my head, but I'll give it a look.
Thank you for asking.

**Comment by fennecdjay** [comment]
Are you working on the README issue?

**Comment by fennecdjay** [comment]
As you can see I found a simple issue: fennecdjay/gwion-ast#5.

**Comment by fennecdjay** [comment]
@all-contributors please add @Pranav2612000  for User Testing.

**Comment by Pranav2612000** [comment]
> Are you working on the README issue?

Yes. I'll send a PR tomorrow.

**Comment by fennecdjay** [comment]
Can't wait!

**Comment by fennecdjay** [comment]
Oh, and please pull from the master, as the README changed with the bot PR.

**Comment by Pranav2612000** [comment]
> Oh, and please pull from the master, as the README changed with the bot PR.

Yup.

**Comment by fennecdjay** [comment]
Closing now as you did great work!

**Comment by fennecdjay** [comment]
Feel free to reopen.
