### ISSUE TITLE
Doc: Installation procedure should be documented in the README

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#179]
After the [first code](https://github.com/fennecdjay/Gwion#executing-your-first-code-hello_worldgw) section, there should be some info about how installing Gwion.

That's basically `make install`.

**Comment by rohanThegreaTT** [comment]
So, is gwion util and ast in this repo? or in different ones?

**Comment by fennecdjay** [comment]
Happy to read you :smile:

> So, is gwion util and ast in this repo? or in different ones?

Those are submodules (they should be in your local version of the repo when you `git submodule update --init util ast`).

I recently updated the Makefile, so `Makefile`, `ast/Makefile` and `util/Makefile` would probably just need a check of `install` and `uninstall` targets.

Sorry I had no time to update the project board/issues, I'm trying to figure out how to leverages teams in Gwion.
By the way, would you join [the organization](https://github.com/orgs/Gwion/)?
Or do you see a better way to handle communication on this project?

**Comment by rohanThegreaTT** [comment]
i'd love to join the organisation! And thanks, This really helps (One of the hardest parts of starting to work on an open source project is learning about how everything works)

**Comment by fennecdjay** [comment]
@rohanThegreaTT do you want to handle this issue? Since its hacktoberfest, I'd like to make it clear wether someone can pick it up or not. Thanks.
