### ISSUE TITLE
scan0_section could use an array of functions

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#182]
For consistency, `scan0_section` should use an array of function, as in e.g. scan1_section.

**Comment by TotallyNotChase** [comment]
is this issue still up for grabs? if so, where exactly is `scan1_section` defined?

**Comment by fennecdjay** [comment]
Totally up for grabs! And pretty easy I think.
You might be able to fix it by 2 new lines and deleting some :smile:
IMHO the best way to code.

You can find `scan1_section` in `src/parse/scan1.c`, look [here](https://github.com/fennecdjay/Gwion/blob/master/src/parse/scan1.c#L578). That's a macro, defined in `ast/include/ast_pass.h` [here](https://github.com/fennecdjay/gwion-ast/blob/master/include/ast_pass.h#L45).
There are other examples of such usage, [here](https://github.com/fennecdjay/gwion/blob/master/src/parse/scan2.c#L555), [here](https://github.com/fennecdjay/gwion/blob/master/src/parse/check.c#L1405) and [here](https://github.com/fennecdjay/gwion/blob/master/src/emit/emit.c#L2041). Thoses cases contains pointers on how to fix this actual issue.

Hope this helps.
Thank you for you interrest.
Looking forward to read you.

**Comment by TotallyNotChase** [comment]
Sorry, could you tell me how I can verify if everything is working fine after the change? I did `make test` and that passed but is there anything else I should check?

**Comment by fennecdjay** [comment]
Not at the moment. Maybe static analysis (in the CI) will find something to complain about, but that IMO quite unlikely here.

**Comment by fennecdjay** [comment]
You make me think that the testing process should be documented [here], alongside the whole [code contribution](https://fennecdjay.github.io/Gwion/Contributing/ContributingCode.html) process. Thank you : smile:
