### ISSUE TITLE
Fix .all-contributorsrc

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#186]
As reported by @TotallyNotChase in #185, the all-contributors badge is currently broken.
However, that's an easy fix, just add the paren where needed [here](https://github.com/fennecdjay/Gwion/blob/master/.all-contributorsrc#L84).

**Comment by evayde** [comment]
Looks like this has been fixed in https://github.com/fennecdjay/Gwion/commit/ed4de6197a9db8a0511eb3783531eccbaf0d1dbf and thus this issue ought to be closed.

**Comment by fennecdjay** [comment]
You're right, Thank you.
