### ISSUE TITLE
find_template_match should be in its own file.

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#192]
Currently [find_template_match](https://github.com/fennecdjay/Gwion/blob/master/src/parse/check.c#L546-L617) is too big and takes a lot of space in `src/parse/check.c`
It would be better to move it to its own file (e.g: src/parse/func_resolve_tmpl.c` with its siblings (ensure_tmpl, check_template_args and probably a few other).
Bonus points for splitting the functions and maybe defining a struct to handle all this.

**Comment by Pranav2612000** [comment]
I'll like to work on this.

**Comment by fennecdjay** [comment]
Please do! That's a great one.

**Comment by Pranav2612000** [comment]
Hey, I need some help. Will I need to create a new header file, which contains the definition of find_template_match, and include this file in check.c ?

**Comment by fennecdjay** [comment]
You're just fine, a new header (with guards e.g :`#__ifndef __TEMPLATE_MATCH__` ... like the other headers) to include in `src/parse/check.c` is the way to go.

**Comment by fennecdjay** [comment]
@Pranav2612000, I was busy yesterday, but I have more time to help now I you still need some :smile:

**Comment by Pranav2612000** [comment]
Just say this message. Will submit a PR by the end of the day. I had a question. My understanding is that static functions can only be used inside the file they are defined in.If this is right, should I move all the static functions (called in func_resolve_tmpl.c) defined in check.c to the new file. Or should I make them non static so that they can be used outside the file too?

**Comment by fennecdjay** [comment]
You should move them and keep them static. If they are also called in check.c, I guess it depends.

**Comment by Pranav2612000** [comment]
I'll move functions which I think are appropriate to the new file. And change some static functions to be non-static in check.c . You could then suggest changes in the PR. Is that 0kay?
