### ISSUE TITLE
Coverage CI should only mail report if variables are set

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#193]
If repository secrets `MAIL_USERNAME` and `MAIL_PASSWORD` are not set, an otherwise successful build could fail. [This step](https://github.com/fennecdjay/Gwion/blob/master/.github/workflows/coverage.yml#L72-L75) should only run if `{{ secrets.MAIL_USERNAME }}` and `{{ secrets.MAIL_PASSWORD }}` are set.

**Comment by TotallyNotChase** [comment]
since github actions doesn't support running an `if: ` on `secrets`. I think it would be better to just check if `github.repository_owner` matches your username and only sending mail if it does.

**Comment by fennecdjay** [comment]
> since github actions doesn't support running an if: on secrets.

Nice catch! I didn't know that.
Your idea about repository owner sounds nice!
