### ISSUE TITLE
Fix async mode in tests

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#196]
This is a pretty easy one :smile:
In [this](https://github.com/fennecdjay/Gwion/blob/master/scripts/test.sh#L190) line, change `-lt` to `-gt`.

----
Job control mode (`set -m`) must be set if the `async` variable is greater than zero, not if it is smaller.
This should fix presentation of tests.

**Comment by umer2001** [comment]
hey,
I am intrested in fixing this bug

**Comment by fennecdjay** [comment]
Great, please do.

**Comment by umer2001** [comment]
sir there is one request,
please correct the spelling of the topic of this repository "hacktoberfest" you missed "k" while typing..,
thankyou.

**Comment by fennecdjay** [comment]
Nice catch, thank you.
