### ISSUE TITLE
Windows CI needs `CC` set in testing step

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#198]
Another easy one!

Just add `CC: gcc` in the `Test` step, just like the step above.

**Comment by umer2001** [comment]
Sir,
can I?

**Comment by a-mere-peasant** [comment]
can I help with this ?

**Comment by fennecdjay** [comment]
I think @umer2001 should do it, as first to respond. I'm pretty sorry @a-mere-peasant (nice username by the way). Stay connected, I have other issues like this one, and it'd be a pleasure to have you as a contributor.
That's the first time I see a concurrency problem as a maintainer :smile:

**Comment by a-mere-peasant** [comment]
@fennecdjay  no problem :)

**Comment by fennecdjay** [comment]
@a-mere-peasant, I understand it's not the same kind of issue, but I'll be AFK for a few hours, so I have no time to write new issues, maybe you'd like to handle #179.
Also, would you be interested in more involved ones?

**Comment by a-mere-peasant** [comment]
> @a-mere-peasant, I understand it's not the same kind of issue, but I'll be AFK for a few hours, so I have no time to write new issues, maybe you'd like to handle #179.
I'll look into it 
> Also, would you be interested in more involved ones?
Sure, I'll try to help with whatever I can
