### ISSUE TITLE
Benchmark action should respect [skip ci]

### ISSUE THREAD

**Issue by fennecdjay** [fennecdjay/Gwion#209]
There is no need to benchmark if the commit states to skip the ci.
I think it is just a matter of adding
```sh
[ -z $(git log -n1 --oneline --grep='[skip ci]' ] && exit 0
```

At the beginning of `call the other repo` step.
See [here](https://github.com/fennecdjay/Gwion/blob/master/.github/workflows/benchmarks.yml#L23)

**Comment by SenorGrande** [comment]
G'Day, could I please work on this issue? Cheers

**Comment by fennecdjay** [comment]
Please do!
