### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#3]
Hey there!

I'm trying to build Gwion,and I'm running into a few issues.

When I do make, I get this error:

> src/instr.c: In function 'Gack':
> src/instr.c:446:5: error: 'for' loop initial declarations are only allowed in
> C99 mode
>      for(int j = 0; j < longest - strlen(name); j++)
>           ^
>           src/instr.c:446:5: note: use option -std=c99 or -std=gnu99 to
>           compile your code
>           make[1]: *** [src/instr.o] Error 1
>           make: *** [silent] Error 2

While you do have the -std=c99 flag defined in your makefile, it's in the LDFLAGS variable, when it
should be in your CFLAGS variable. that goes for the -g flag, the -O3 flag, and possibly the -m flags (though I'm not as familiar with those.)

Personally, I don't like initial for loop declarations. I would just declare j before. For reference, Soundpipe borrows a lot of concepts from the guys [suckless](http://suckless.org/coding_style). If you haven't looked at it yet, I would check it out. They write really clean C code.

---

Okay, so I've now made those changes and can move on. The new error I get has to do with M_PI being undeclared. As it turns out, M_PI is not part of c99, so if you want to use you have to declare it manually like so:

> #ifndef M_PI
> #define M_PI		 3.14159265358979323846
> #endif

I put this in src/instr.c (as an aside, I see you have your local includes before your system-wide includes. I would reverse this.)

This solves that error!

---

Finally, I learn that I need libsoundio, which I do not have.

This one I can't really fix quickly because I don't want to install libsoundio. It would be great to make this an optional dependency. By default, [sporth](https://www.github.com/paulbatchelor/sporth.git) only does offline rendering using libsndfile, but there is optional support for JACK. This has served me quite well (except for those rare situations where I can't even get libsndfile to install correctly on a machine).

This project looks very cool. I look forward to seeing it develop. 

-P

**Comment by fennecdjay** [comment]
Not much time to read rigth now, but I'll take great care if what you wrote.
I think I can make output straight to alsa, or a soundfile, I'll check that ASAP.

---

to be continued...

**Comment by PaulBatchelor** [comment]
@fennecdjay yup, this is a wall of text. I'm going to break this up into smaller issues, then close this one.

**Comment by PaulBatchelor** [comment]
Closing this, continuing this discussion with the PR found here: #7
