### ISSUE TITLE
Integration with Sporth

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#4]
It would be very cool if you were able to implement Sporth as an optional UGen for Gwion. 

I built a [Sporth UGen for ChucK](http://pbat.ch/proj/chorth.html) last year, so you can look at that for inspiration. In practice, I've found that the two paradigms work quite well for one another.

**Comment by fennecdjay** [comment]
Oh yeah ;-)
ASAP.

**Comment by fennecdjay** [comment]
I'm probably missing something, but it seems the link you provide leads lack a link to the source,
wich I failed to find in your Github repos either. It is pretty sure that having your sources as a model would shorten the time to get a **Sporth** UGen up and working.

**Comment by PaulBatchelor** [comment]
Oh yeah, it has moved. It now resides in util/chorth instead of the top level directory...

**Comment by fennecdjay** [comment]
Just found it. Thank you.

**Comment by PaulBatchelor** [comment]
Let me know if you have troubles. No other human other than myself has ever tried using the Sporth API, so there may be some undocumented things. 

Just to make this issue more actionable, I would recommend doing a bare minimum Sporth ugen that has a method called "parse", which parses a Sporth strings. More things can come later (p values, tables, variables, etc...)

**Comment by fennecdjay** [comment]
I'm beginning to have something that compile, yet I have to implement sound,
wether I link with system libsporth or local libsporth.a, but at runtime, I hit this:
```
./gwion: symbol lookup error: /usr/lib/Gwion/plug/gworth.so: undefined symbol: plumber_register
```

any hints?
Maybe I have to build a dynamic sporth lib.

**Comment by fennecdjay** [comment]
Right now, with dinamically linked sporth lib, things get better, but the *ptest* example, modified for gwion keeps teling me:
```
Stack limit of 32 reached, cannot push float value.
```
Still searching was I'm doing wrong.

**Comment by fennecdjay** [comment]
Things are getting better now, after compiling a dynamic *Sporth* library, it runs OK.
plug directory in *Gwion* is now a submodule, linked to *Gwion-plug*, and is the place to find the *Sporth* plugin.
I hope you can do something with this.
If you want and if I manage to get things clear on the dynamic library thing, I might make a pull request in *Sporth*.

**Comment by PaulBatchelor** [comment]
There is definitely a way to get it working with a static library and you
shouldn't need to compile a dynamic library. The trick is the order that
you link things in with GCC or LD. See my makefile recipe in  chorth.

**Comment by fennecdjay** [comment]
Thanks for the hint. I'll give that a look.

**Comment by fennecdjay** [comment]
It looks like it is working with the static lib.
I made some updates to [the plugins](https://github.com/fennecdjay/Gwion-plug).
But I must admit I have some troubles with submodule usage, so please check you use master branch of [Gwion-plug](https://github.com/fennecdjay/Gwion-plug).
I also made the dev branch Gwion's default branch, until further fixes.
If you run into trouble with [Sporth plugin](https://github.com/fennecdjay/Gwion-plug/tree/master/sporth) please make an issue in [Gwion-plug](https://github.com/fennecdjay/Gwion-plug) as it is where this conversation belongs now.

**Comment by PaulBatchelor** [comment]
Cool. I'll close this ticket then.
