### ISSUE TITLE
Floating-point precision 

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#49]
Gwion's autoconf is telling me that I need to compile soundpipe with doubles support. Is there any way to get Gwion to support floating point precision in addition to double precision?

**Comment by fennecdjay** [comment]
@PaulBatchelor : YES!
The README needs serious improvment, to prevent such cases.
Concerning your issue, pass it `--no-double` as argument.
Also while still a bit unclear,
```sh
./configure --help
```
migth give you some info.
 Thanks for the care.

**Comment by fennecdjay** [comment]
Commit [d31cf00](https://github.com/fennecdjay/Gwion/commit/d31cf00bf6f335e6d9df659e6b1f5b2c6800aa23) now defines **float** as default float type, to match  [Soundpipe](https://github.com/PaulBatchelor/Soundpipe)'s defaults. So if you pull, there'll be no more need to pass `no-double` argument.
Glad you give Gwion a chance 😄

**Comment by fennecdjay** [comment]
@PaulBatchelor  did you get it working?

**Comment by PaulBatchelor** [comment]
When I run "./configure --no-double", I get:

> ls: cannot access ../Soundpipe/modules/data: No such file or directory

**Comment by fennecdjay** [comment]
I see.  I'm very confused when it comes to writing docs. But they are really lacking now...
Anyway, your problem is that `configure` needs to know where your soundpipe's `module/data` is. This is set by `--data`, so should try either
```sh
./configure --data=you_sp_module_data_directory
```
or
```sh
./configure --data you_sp_module_data_directory
```

Thanks by the way, I just noticed it didn't return error when this fails. :smile:


-----------

If you think of any location that would be a better default for this, let me know.

**Comment by PaulBatchelor** [comment]
Cool that compiles.  I had to supply an absolute path to the data dir and couldn't use "~". Is there any reason why there's a dependency on my data files in Soundpipe?

**Comment by fennecdjay** [comment]
The reson of this dependency is that gwion's build system generates it's soundpipe part (ugen/soundpipe.c) using these lua files.
I've been thinking providing these, but that enables to be always up-to-date with your repo.
That's how I've been finding [this](https://github.com/fennecdjay/Gwion/issues/49#issuecomment-289624099) issue.

I'm gonna investigate the "~" issue.

**Comment by PaulBatchelor** [comment]
What's the advantage of having the user generate that file? Seems to me like an extra step.

**Comment by fennecdjay** [comment]
IMO, it makes the user able to use wich branch of your project it wants. Maybe I'm wrong.
Anyway, that `configure` stuff is still a work in progress, to I gladly take any advice.

**Comment by fennecdjay** [comment]
> I'm gonna investigate the "~" issue

Well, it seems to work on my platform, so without more input, I won't be able to fix that. 😢

**Comment by PaulBatchelor** [comment]
I would suggest having a default generated soundpipe.c that you generating on your computer using the "master" branch of soundpipe. Having these little extra steps is not encouraging to the impatient user who wants things up and running as fast as possible.

**Comment by fennecdjay** [comment]
You're rigth, I'll probably just enable generation on demand in configure.

**Comment by fennecdjay** [comment]
Done (this long).
