### ISSUE TITLE
Use upstream version of Soundpipe instead of fork

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#5]
Forks of Soundpipe are cool! I like people hacking on Soundpipe.

However, it seems like the only thing you are changing is define SPFLOAT to be double instead of float. 
It doesn't seem like it's worth the effort to maintain a fork of SP just to do that. Plus it'll be confusing to users that will want to use your software.

If it's just precision that you want, I can easily do some fixes in SP so that you can choose floats or doubles in the config file.

**Comment by fennecdjay** [comment]
That would be so great!
If you already got some kind of fix, please go, I'd gadly use SP uptream version.
I'm still wondering what is the best way to do so.

**Comment by PaulBatchelor** [comment]
I don't have any fix implemented yet, but basically the user would be able to decide if they'd want floats or doubles, and Gwion wouldn't be aware of the data type since you'd just be using SPFLOAT.

**Comment by PaulBatchelor** [comment]
@fennecdjay do you use Trello at all? I have a Soundpipe trello for project management, and I would love to have you on the team!

**Comment by fennecdjay** [comment]
I had never herad of Trello. but would gadly join the team.

**Comment by fennecdjay** [comment]
You migth be able to find me on [trello](http://trello.com), as now have an account.

**Comment by PaulBatchelor** [comment]
I have added you on my Trello I think!

**Comment by fennecdjay** [comment]
Yes you did!

**Comment by fennecdjay** [comment]
I made a few fixes to Gwion, now it has a **USE_DOUBLE** variable in *config.def.mk*.
if unset, it compiles using **float**, and this is the *new* default.
Yet I've still got to improve the build system, I seems this works already with upstream Soundpipe.
Letting this issue opened because I don't know if you will see it if I close it.

also fixing the *README*.

**Comment by PaulBatchelor** [comment]
@fennecdjay does this mean you are linking with libsoundpipe now, or are you just using floats by default in your fork?

**Comment by fennecdjay** [comment]
It links by default with vanilla soundpipe.
normally, just define jour driver in config.mk and type make.

**Comment by fennecdjay** [comment]
let me know, so that I can close the issue.

**Comment by PaulBatchelor** [comment]
I'm happy with that. Close away!

**Comment by fennecdjay** [comment]
Great!
closing now.
