### ISSUE TITLE
No sound with JACK driver

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#9]
Hey again!

So, things compile, but I'm not getting sound from your sine example. 
It runs, it connects to speakers, but it is completely silent. 

Any idea what that could be?

Thanks,

-P

**Comment by fennecdjay** [comment]
I **really** don't know.
Just got home, pushed a few changes I made, merged your stuff, compiled and I still get sound.
I'll check that.

By the way, does the sndfile driver work correctly for  you?

Anyway, I'm so happy you can compile now.

**Comment by PaulBatchelor** [comment]
how do I use the sndfile driver? what are the config.mk settings, and what do I run on the command line to test?

**Comment by fennecdjay** [comment]
look at the output of 
```
./gwion --help
```
or
 ```
./gwion -?
```

you should get something like:
```
usage: Gwion <options>
  option can be any of:
GLOBAL options:  <argument>  : description
  --help,   -?               : this help
VM     options:
  --add,    -+   <file>      : add file
  --rem,    --   <shred id>  : remove shred
  --quit    -q               : quit the vm
UDP    options:
  --host    -h    <string>   : set host
  --port    -p    <number>   : set port
  --loop    -l    <0 or 1>   : loop state (0 or 1)
  --alone   -a               : standalone mode. (no udp)
DRIVER options:
  --driver  -d    <string>   : set the driver (one of: alsa jack soundio portaudio file dummy silent raw)
  --sr      -s    <number>   : set samplerate
  --bufnum  -n    <number>   : set number of buffers
  --bufsize -b    <number>   : set size   of buffers
  --chan    -g    <number>   : (global) channel number
  --in      -i    <number>   : number of  input channel
  --out     -o    <number>   : number of output channel
  --card    -c    <string>   : card identifier or output file (depending on driver)
  --raw     -r    <0 or 1>   : enable raw mode (file and soundio only)
  --format  -f    <string>   : soundio format (one of: S8 U8 S16 U16 S24 U24 S32 U32 F32 F64)
  --backend -e    <string>   : soundio backend (one of: jack pulse alsa core wasapi dummy)
```

so if you try
```
./gwion -d sndfile -c /tmp/gwion_out examples/sine.gw 
```
you should end with */tmp.gwion_out_00.wav*  and */tmp/gwion_out_01.wav* each containing a one second sine wave.

It work on my station, I hope it will on yours.

**Comment by PaulBatchelor** [comment]
This is what I get:

paul@darkstar:~/src/Gwion$ ./gwion -d sndfile -c gwion_out examples/sine.gw
registering output_0
registering output_1
system:playback_1
system:playback_2
zombified - calling shutdown handler
*** Error in `./gwion': corrupted double-linked list: 0x00007f0cf8000bb0 ***
Inconsistency detected by ld.so: dl-open.c: 224: dl_open_worker: Assertion
`_dl_debug_initialize (0, args->nsid)->r_state == RT_CONSISTENT' failed!

**Comment by PaulBatchelor** [comment]
by the way, I am using the "dev" branch.

**Comment by fennecdjay** [comment]
**My mistake**.
the correct flag is *file*.
so the command is
```
./gwion -d file -c gwion_out examples/sine.gw
```
if you the the *--raw* or *-r* flag, this is supposed to generate a **SPA** file.

you do wel for the "dev" branch, I don't plan to push anything on "master" branch before you can hear something from this program. 

Do you have plugins installed? (because it might be related to that dl-open error)

**Comment by fennecdjay** [comment]
I'd really like you to get a least one driver working.
I'm afraid that on my platform every drivers seem to work correctly, so in the current state, I'm don't see how I quite don't see how I can help.
I guess I could fill the jack driver with debug statements, I you don't mind sending me back the output.

**Comment by PaulBatchelor** [comment]
@fennecdjay That new command you sent me seems to write files. However, the file is silence and is very short (it isn't 5 seconds).

When I run soxi on it I get this:

paul@darkstar:~/src/Gwion$ soxi gwion_out_00.wav

```
Input File     : 'gwion_out_00.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 24-bit
Sample Encoding: 24-bit Signed Integer PCM

```

Which smells like it's not writing to disk properly.

**Comment by PaulBatchelor** [comment]
Did some googling on the jack error, and this was very informative:

> paul@darkstar:~/src/Gwion$ strace ./gwion -d jack examples/sine.gw 2>&1 | grep
> open
> open("/usr/local/share/sporth/plugins/tls/x86_64/libm.so.6",
>         O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/local/share/sporth/plugins/tls/libm.so.6", O_RDONLY|O_CLOEXEC) = -1
> ENOENT (No such file or directory)
>     open("/usr/local/share/sporth/plugins/x86_64/libm.so.6",
>             O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
>     open("/usr/local/share/sporth/plugins/libm.so.6", O_RDONLY|O_CLOEXEC) = -1
>     ENOENT (No such file or directory)
>     open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
>     open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libsndfile.so.1",
>             O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
>     open("/usr/lib64/libsndfile.so.1", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libdl.so.2", O_RDONLY|O_CLOEXEC) =
>     -1 ENOENT (No such file or directory)
>     open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/librt.so.1", O_RDONLY|O_CLOEXEC) =
>     -1 ENOENT (No such file or directory)
>     open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libjack.so.0", O_RDONLY|O_CLOEXEC) =
>     -1 ENOENT (No such file or directory)
>     open("/usr/lib64/libjack.so.0", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libpthread.so.0",
>             O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
>     open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libc.so.6", O_RDONLY|O_CLOEXEC) = -1
>     ENOENT (No such file or directory)
>     open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/lib64/tls/x86_64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT
>     (No such file or directory)
>     open("/usr/lib64/tls/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No
>             such file or directory)
>     open("/usr/lib64/x86_64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No
>             such file or directory)
>     open("/usr/lib64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/lib64/libvorbisenc.so.2", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/lib64/libvorbis.so.0", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/lib64/libogg.so.0", O_RDONLY|O_CLOEXEC) = 3
>     open("/usr/local/share/sporth/plugins/libdb-4.8.so", O_RDONLY|O_CLOEXEC) =
>     -1 ENOENT (No such file or directory)
>     open("/lib64/libdb-4.8.so", O_RDONLY|O_CLOEXEC) = 3
>     open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 4
>     open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 4
>     open("/usr/local/share/sporth/plugins/libnss_files.so.2",
>             O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
>     open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
>     open("/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 4
>     open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 4
>     open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 4
>     open("/proc/cpuinfo", O_RDONLY)         = 4
>     openat(AT_FDCWD, "/usr/lib/Gwion/plug",
>             O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such
>                 file or directory)
>             open("/home/paul/src/Gwion/examples/sine.gw", O_RDONLY) = 6
>             open("/usr/local/share/sporth/plugins/libgcc_s.so.1",
>                     O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or
>                         directory)
>                     open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 8
>                     open("/usr/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 8

For some reason, it's looking for libraries in strange places. This could be an issue on my end...

**Comment by fennecdjay** [comment]
I just retried the sndfile driver stuff, and I get a one second wav file, with sound.
It is not supposed to be 5 seconds anyway.
Maybe that is SPFLOAT type related.
I think I'll make Gwion able to build with float by default, it might help.
I'll probably do that tomorrow evening.

**Comment by PaulBatchelor** [comment]
I done goofed on my system. Rebooted, this looks better:

> open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/libsndfile.so.1", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/libjack.so.0", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/tls/x86_64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib64/tls/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib64/x86_64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib64/libFLAC.so.8", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/libvorbisenc.so.2", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/libvorbis.so.0", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib64/libogg.so.0", O_RDONLY|O_CLOEXEC) = 3
> open("/lib64/libdb-4.8.so", O_RDONLY|O_CLOEXEC) = 3
> open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 4
> open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 4
> open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
> open("/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 4
> open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 4
> open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 4
> open("/proc/cpuinfo", O_RDONLY)         = 4
> openat(AT_FDCWD, "/usr/lib/Gwion/plug", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/home/paul/src/Gwion/examples/sine.gw", O_RDONLY) = 6
> Inconsistency detected by ld.so: dl-open.c: 224: dl_open_worker: Assertion `_dl_debug_initialize (0, args->nsid)->r_state == RT_CONSISTENT' failed!

Now it's complaining about /usr/lib/Gwion/plug (it doesn't exist). and libflac.

**Comment by PaulBatchelor** [comment]
fixed gwion plug error... now just libflac. huh. Let me look at this later...

**Comment by PaulBatchelor** [comment]
I have sound now! See my pull request.
